jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo hello from macOS
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows 2016
- job: Windows2012R2
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: echo hello from Windows 2012r2
- job: Windows1803
  pool:
    vmImage: 'win1803'
  steps:
  - script: echo hello from Windows 1803 container
