jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo hello from Linux
  - script: cat /proc/cpuinfo
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo hello from macOS
  - script: sw_vers
  - script: system_profiler SPHardwareDataType
  - script: system_profiler
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows 2016
  - script: systeminfo
- job: Windows2012R2
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - script: echo hello from Windows 2012r2
  - script: systeminfo
- job: Windows1803
  pool:
    vmImage: 'win1803'
  steps:
  - script: echo hello from Windows 1803 container
  - script: systeminfo
